// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (c) 2000-2002,2005 Silicon Graphics, Inc.
 * Copyright (C) 2017 Oracle.
 * All Rights Reserved.
 */
#ifndef __SCXFS_ERRORTAG_H_
#define __SCXFS_ERRORTAG_H_

/*
 * error injection tags - the labels can be anything you want
 * but each tag should have its own unique number
 */

#define SCXFS_ERRTAG_NOERROR				0
#define SCXFS_ERRTAG_IFLUSH_1				1
#define SCXFS_ERRTAG_IFLUSH_2				2
#define SCXFS_ERRTAG_IFLUSH_3				3
#define SCXFS_ERRTAG_IFLUSH_4				4
#define SCXFS_ERRTAG_IFLUSH_5				5
#define SCXFS_ERRTAG_IFLUSH_6				6
#define SCXFS_ERRTAG_DA_READ_BUF				7
#define SCXFS_ERRTAG_BTREE_CHECK_LBLOCK			8
#define SCXFS_ERRTAG_BTREE_CHECK_SBLOCK			9
#define SCXFS_ERRTAG_ALLOC_READ_AGF			10
#define SCXFS_ERRTAG_IALLOC_READ_AGI			11
#define SCXFS_ERRTAG_ITOBP_INOTOBP			12
#define SCXFS_ERRTAG_IUNLINK				13
#define SCXFS_ERRTAG_IUNLINK_REMOVE			14
#define SCXFS_ERRTAG_DIR_INO_VALIDATE			15
#define SCXFS_ERRTAG_BULKSTAT_READ_CHUNK			16
#define SCXFS_ERRTAG_IODONE_IOERR				17
#define SCXFS_ERRTAG_STRATREAD_IOERR			18
#define SCXFS_ERRTAG_STRATCMPL_IOERR			19
#define SCXFS_ERRTAG_DIOWRITE_IOERR			20
#define SCXFS_ERRTAG_BMAPIFORMAT				21
#define SCXFS_ERRTAG_FREE_EXTENT				22
#define SCXFS_ERRTAG_RMAP_FINISH_ONE			23
#define SCXFS_ERRTAG_REFCOUNT_CONTINUE_UPDATE		24
#define SCXFS_ERRTAG_REFCOUNT_FINISH_ONE			25
#define SCXFS_ERRTAG_BMAP_FINISH_ONE			26
#define SCXFS_ERRTAG_AG_RESV_CRITICAL			27
/*
 * DEBUG mode instrumentation to test and/or trigger delayed allocation
 * block killing in the event of failed writes. When enabled, all
 * buffered writes are silenty dropped and handled as if they failed.
 * All delalloc blocks in the range of the write (including pre-existing
 * delalloc blocks!) are tossed as part of the write failure error
 * handling sequence.
 */
#define SCXFS_ERRTAG_DROP_WRITES				28
#define SCXFS_ERRTAG_LOG_BAD_CRC				29
#define SCXFS_ERRTAG_LOG_ITEM_PIN				30
#define SCXFS_ERRTAG_BUF_LRU_REF				31
#define SCXFS_ERRTAG_FORCE_SCRUB_REPAIR			32
#define SCXFS_ERRTAG_FORCE_SUMMARY_RECALC			33
#define SCXFS_ERRTAG_IUNLINK_FALLBACK			34
#define SCXFS_ERRTAG_MAX					35

/*
 * Random factors for above tags, 1 means always, 2 means 1/2 time, etc.
 */
#define SCXFS_RANDOM_DEFAULT				100
#define SCXFS_RANDOM_IFLUSH_1				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IFLUSH_2				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IFLUSH_3				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IFLUSH_4				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IFLUSH_5				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IFLUSH_6				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_DA_READ_BUF				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_BTREE_CHECK_LBLOCK			(SCXFS_RANDOM_DEFAULT/4)
#define SCXFS_RANDOM_BTREE_CHECK_SBLOCK			SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_ALLOC_READ_AGF			SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IALLOC_READ_AGI			SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_ITOBP_INOTOBP			SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IUNLINK				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IUNLINK_REMOVE			SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_DIR_INO_VALIDATE			SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_BULKSTAT_READ_CHUNK			SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_IODONE_IOERR				(SCXFS_RANDOM_DEFAULT/10)
#define SCXFS_RANDOM_STRATREAD_IOERR			(SCXFS_RANDOM_DEFAULT/10)
#define SCXFS_RANDOM_STRATCMPL_IOERR			(SCXFS_RANDOM_DEFAULT/10)
#define SCXFS_RANDOM_DIOWRITE_IOERR			(SCXFS_RANDOM_DEFAULT/10)
#define SCXFS_RANDOM_BMAPIFORMAT				SCXFS_RANDOM_DEFAULT
#define SCXFS_RANDOM_FREE_EXTENT				1
#define SCXFS_RANDOM_RMAP_FINISH_ONE			1
#define SCXFS_RANDOM_REFCOUNT_CONTINUE_UPDATE		1
#define SCXFS_RANDOM_REFCOUNT_FINISH_ONE			1
#define SCXFS_RANDOM_BMAP_FINISH_ONE			1
#define SCXFS_RANDOM_AG_RESV_CRITICAL			4
#define SCXFS_RANDOM_DROP_WRITES				1
#define SCXFS_RANDOM_LOG_BAD_CRC				1
#define SCXFS_RANDOM_LOG_ITEM_PIN				1
#define SCXFS_RANDOM_BUF_LRU_REF				2
#define SCXFS_RANDOM_FORCE_SCRUB_REPAIR			1
#define SCXFS_RANDOM_FORCE_SUMMARY_RECALC			1
#define SCXFS_RANDOM_IUNLINK_FALLBACK			(SCXFS_RANDOM_DEFAULT/10)

#endif /* __SCXFS_ERRORTAG_H_ */
